Курсовая работа.
PaFxPaF/WUC-421 pull request #7
Opened 2024-05-06 15:23 UTC by PaFxPaF

В данном курсовом проекте ставится задача разработать РБД в СУБД Microsoft SQL Server по заданной теме, формализующую заданную предметную область (ПрО, domain). Проектирование РБД проводится с помощью метода «Сущность-связь». Проверка построенной модели РБД осуществляется с помощью метода нормализации отношений. Пояснительная записка должна содержать пункты по проектированию РБД и пункты по разработке РБД в СУБД Microsoft SQL Server: разработка скриптов на создание и заполнение РБД, разработка необходимых функций, процедур, триггеров и представлений (views).

2024-05-07 14:57 UTC, MarinaPaley requested changes
Оформление
1. Убежала Цель
2. Точка в конце не ставится (подпись рисунка).
3. Выравнивание слева для надписи у таблицы. точка в конце надписи не ставится
4. Дошло до сути. ER - диаграмма неправильная. Товар лежит на складе в ячейках. В одной ячейке - много продуктов? Тогда это связь многие-ко-многим. Заказы. На диаграмме нарисована связь многие-ко-многим, что правильно (почти правильно нарисовано). Но! Такая связь не может быть реализована реляционной СУБД. Нужно ее разорвать с помощью новой таблицы, которая будет содержать свой ID, ID таблицы слева и ID таблицы справа. Про контрагентов не до конца понимаю. Это те, что покупает, ID контрагента в таблице товар точно не нужен....

2024-05-09 16:19 UTC, PaFxPaF commented
Исправлено.

2024-05-14 16:45 UTC, MarinaPaley commented
@PaFxPaF Исправьте, пожалуйста, СУБД Microsoft SQL Server на СУБД PostgreSQL.

2024-05-14 16:53 UTC, MarinaPaley requested changes
Добавьте
1. Ограничения уникальности, там, где это Вы прописали в таблицах
2. Ограничение, что дата окончания действия больше, чем дата начала действия
3. Ограничение Величина скидки больше или равна 0
4. Ограничение Количество больше 0
5. Написать, почему же все отношения находятся в 3НФ

Остальное все хорошо, можно защищать)

2024-05-14 20:10 UTC, merged